### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by oscarotero** [middlewares/base-path-router#1]
Hi. I'd like to propose some improvements to this package in order to be more inline with the rest of the middlewares/* packages. Let me know what do you think.

* Change the name to `PathRouter` or `BasePathRouter`, because it describes better the purpose of this middleware (it's just a router).
* Create an option to strip the path, to be able to enable/disable this feature
* Instead accept only middlewares, accept any value and do not execute it. Save the value in a request attribute to execute it later, using [request-handler](https://github.com/middlewares/request-handler). This is how works the other routers (aura-router, fast-route), allowing to use a psr-11 container to lazy load the handlers.

Thanks! 😄

**Comment by franzliedke** [comment]
Thank you for the feedback!

> Change the name...

Sure. Of you suggestions, I think I'd go with `BasePathRouter`. Alternatively, what do you think about `PrefixRouter`?

> Create an option to strip the path, to be able to enable/disable this feature

Can you elaborate on this one? What do you hope to gain? IMO, stripping the path is the whole point of this middleware: group a stack of (routing) middleware under a common prefix, without them having to know that's where they are running.

> using request-handler

Thanks, I will take a look.

I am about to go offline for a couple of days. I will let you know when these are taken care of.

**Comment by oscarotero** [comment]
The ability to do not strip the prefix router allows to use this middleware as a simple and fast router when attributes or regular expressions are not needed.

Other use case is to emulate the same behaviour that Middleland has: execute some middlewares only under some paths. Example:

```php
$middlewares[] = new BasePathRouter([
    '/admin' => new HttpDigestAuthentication($users),
    '/images' => new ImageManipulator()
]);

$middlewares[] = new RequestHandler();
```
Because `RequestHandler` can handle not only RequestHandlers but also Middlewares (allowing to continue with the next middleware), you can use multiple routers in the same stack.

And about the name, I like both `BasePathRouter` and `PrefixRouter`. I'd inclined to `BasePathRouter` only because this term is used in the `BasePath` middleware, having a similar function, so it is more consistent. But if you prefer `PrefixRouter`, I'm ok too. I leave it to your choice.

**Comment by franzliedke** [comment]
@oscarotero I spent some time today trying to implement your suggestion, especially in regards to integrating with the `RequestHandler` middleware.

It doesn't work, though.

For path prefixing to work properly, I need to restore the old prefix when passing on control to the fallback handler (that is passed to the middleware). *Only when dispatching to the prefix-specific middleware*, should the prefix be stripped. With your suggestion, both dispatching to the middleware and to the fallback happens to the request handler passed to `PrefixRouter`. What to do now? :thinking:

**Comment by oscarotero** [comment]
An idea:

* If the path does not match with any prefix provided, the middleware should return a 404 response (as do the other router-based middlewares)
* There could be an option to define a default handler to avoid that behaviour. This could be defined using the `->defaultHandler($handler)` option, that does not strip the prefix but insert the handler in the request attribute and continue to the next middleware.

```php
$middlewares[] = (new PrefixRouter($prefixes))
    ->defaultHandler($notFoundHandler);
```

Does this cover your use case?

**Comment by franzliedke** [comment]
Absolutely! Not sure why I didn't think of that. :)

**Comment by franzliedke** [comment]
Okay, I've taken care of that.

All suggestions from this issue, except for the config flag, are now taken care of.
I used to be :-1: on that, but given that this is now a router, I guess this behavior (the *prefix stripping*) should indeed be configurable.

@oscarotero When you have time, please have a look at the repo again (or really, the tests, as they describe the functionality quite clearly IMO). Let me know what else you need, and what further steps I should take to get this transferred to your org. :smile:

**Comment by oscarotero** [comment]
The code looks great. Just need to add the `defaultHandler` and `stripPrefix` options, right?

Other minor thing (is a matter of taste, so change it only if you want), is that I usually use static methods for helpers like `unprefixedRequest` and `getNormalizedPath`.

Once you feel confortable with it, just transfer the repo to "middlewares" org and I will publish it. You will continue being a maintainer.

**Comment by franzliedke** [comment]
Okay, options added, tested and documented.
I also renamed to `base-path-router` to be consistent with the existing `base-path` middleware (which could actually be used as a dependency here... :thinking:).

I consider this closed.

Will try to transfer now. :smile:

**Comment by franzliedke** [comment]
@oscarotero Not allowed to transfer ("You don’t have the permission to create repositories on middlewares").

I added you as a collaborator to this repo, can you take care of it? :pray:

**Comment by oscarotero** [comment]
I accepted the invitation but cannot transfer the repo either. I'm adding you to the middlewares colaborators.

Once the repository is transfered, I'd like to make a quick review before tag the first version.

**Comment by franzliedke** [comment]
Done. Thanks for your support! :smile:
