### ISSUE TITLE
Some changes before release v1.0

### ISSUE THREAD

**Issue by oscarotero** [middlewares/base-path-router#2]
@franzliedke I've made some changes to inline this package with the rest of middlewares:

- Added an option to customize the attribute name used to store the request handler (this is something that is available in other routers)
- The default handler is treated like the rest of handlers (saved in an attribute, instead execute it directly)
- Some changes in code style and tests

Let me know your opinion. Any suggestion is welcome.
Thanks!

**Comment by franzliedke** [comment]
Cool, thank you!

Will release v0.1.0 soon and give it some time for public feedback.
